"""
Django settings for WikiProject project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import boto3
ssm_client = boto3.client('ssm')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ssm_client.get_parameter(Name='/Django/secret_key')['Parameter']['Value']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'false').lower() == 'true'

ALLOWED_HOSTS = ["*"]

# カスタム変数
USE_DSQL = os.environ.get('USE_DSQL', 'false').lower() == 'true'
COGNITO_USER_POOL_ID = ssm_client.get_parameter(Name='/Cognito/user_pool_id')['Parameter']['Value']
COGNITO_CLIENT_ID = ssm_client.get_parameter(Name='/Cognito/client_id')['Parameter']['Value']
COGNITO_CLIENT_SECRET = ssm_client.get_parameter(Name='/Cognito/client_secret')['Parameter']['Value']
AWS_REGION = boto3.session.Session().region_name

# API Gatewayを直接呼び出す用
FORCE_SCRIPT_NAME = os.environ.get('SCRIPT_NAME', '')

# Application definition

if USE_DSQL:
  INSTALLED_APPS = [
    'accounts.apps.AccountsConfig'  # Custom app
  ]
  MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'accounts.middleware.CognitoAuthMiddleware',  # Cognito JWT authentication
  ]

else:
  INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts.apps.AccountsConfig'  # Custom app
  ]

  MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.middleware.CognitoAuthMiddleware',  # Cognito JWT authentication
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
  ]

ROOT_URLCONF = 'WikiProject.urls'

TEMPLATES = [
  {
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [],
    'APP_DIRS': True,
    'OPTIONS': {
      'context_processors': [
        'django.template.context_processors.request',
        'django.contrib.auth.context_processors.auth',
        'django.contrib.messages.context_processors.messages',
      ],
    },
  },
]

WSGI_APPLICATION = 'WikiProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if USE_DSQL:
  # Aurora DSQL configuration for Lambda
  # Reference: https://github.com/awslabs/aurora-dsql-django
  DSQL_CLUSTER_ENDPOINT = ssm_client.get_parameter(Name='/DSQL/cluster_endpoint')['Parameter']['Value']
  DATABASES = {
    'default': {
      'ENGINE': 'aurora_dsql_django',
      'HOST': DSQL_CLUSTER_ENDPOINT,
      'USER': 'admin',  # DSQL username is always 'admin'
      'NAME': 'postgres',  # DSQL database name is always 'postgres'
      'OPTIONS': {
        'sslmode': 'require',
        'region': AWS_REGION,
      }
    }
  }
else:
  DATABASES = {
    'default': {
      'ENGINE': 'django.db.backends.sqlite3',
      'NAME': BASE_DIR / 'db.sqlite3',
    }
  }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
  {
    'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
  },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static_local']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
