# Generated by Django 5.2.8 on 2025-11-28 15:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(db_index=True, max_length=127)),
                ('priority', models.FloatField(default=0)),
                ('title', models.CharField(max_length=127)),
                ('public', models.BooleanField(default=False)),
                ('edit_permission', models.BooleanField(default=False)),
                ('share', models.BooleanField(default=False)),
                ('share_edit_permission', models.BooleanField(default=False)),
                ('share_code', models.CharField(blank=True, max_length=127, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]+$')])),
                ('text', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='wiki_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wiki_pages',
                'indexes': [models.Index(fields=['user', '-last_updated'], name='wiki_pages_user_id_3b8f04_idx'), models.Index(fields=['public', '-last_updated'], name='wiki_pages_public_286749_idx'), models.Index(fields=['share_code'], name='wiki_pages_share_c_9bf5b9_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'slug'), name='wiki_slug_unique')],
            },
        ),
    ]
