# Generated by Django 5.2.8 on 2025-11-29 15:22

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetable',
            name='text',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
    ]
