# Generated by Django 5.2.8 on 2025-11-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_alter_pagetable_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetable',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
